{
 "title": "Alerts - Linux Nodes",
 "description": "Alerts for Linux Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "linux"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "IoTChain status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"iotchain\"}"
    }
   ]
  },
  {
   "title": "prometheus status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "mysql status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "node status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Linux Nodes Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes{mountpoint=~\"/\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{mountpoint=~\"/\"}  / 1024 / 1024))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Nodes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}