{
 "title": "iotchain",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"iotchain\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"iotchain\"})"
    }
   ]
  },
  {
   "title": "Best Block Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "iotchain_BestBlockNumber_active"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"iotchain\"}*1000"
    }
   ]
  },
  { "title": "HttpService QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Http Sever QPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_http_server_request_count[5m])"
    }
   ]
  },
  {
   "title": "Http Server Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_http_server_response_duration_seconds_sum[5m])/rate(iotchain_http_server_response_duration_seconds_count[5m])"
    }
   ]
  },
  { "title": "Get QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "getBlockBodyByHash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBlockBodyByHash_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getBlockHeaderByHash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBlockHeaderByHash_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "getBlockBodyByHash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBlockBodyByHash_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getBlockByNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBlockByNumber_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getBlockHeaderByNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBlockHeaderByNumber_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getHashByBlockNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getHashByBlockNumber_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getBestBlockNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getBestBlockNumber_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getReceiptsByHash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getReceiptsByHash_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getTotalDifficultyByHash",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getTotalDifficultyByHash_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "getTotalDifficultyByNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_getTotalDifficultyByNumber_seconds_sum[1m])"
    }
   ]
  },
  { "title": "Put QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "putBestBlockNumber",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_putBestBlockNumber_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "putBlockHeader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_putBlockHeader_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "putBlockBody",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_putBlockBody_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "putReceipts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_putReceipts_seconds_sum[1m])"
    }
   ]
  },
  {
   "title": "putBlockAndReceipts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(iotchain_putBlockAndReceipts_seconds_sum[1m])"
    }
   ]
  }
 ]
}