// Load the config generated by scalajs-bundler
const path = require('path');
const config = require('./scalajs.webpack.config');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const merge = require('webpack-merge');

module.exports = merge(config, {
  resolve: {
    modules: [ path.resolve(__dirname, 'node_modules') ]
  }
});
